# Generated by Django 5.0.3 on 2024-04-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guest_name', models.CharField(max_length=100)),
                ('Guest_email', models.CharField(max_length=100)),
                ('Guest_number', models.CharField(max_length=10)),
                ('Guest_password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
