# Generated by Django 5.0.3 on 2024-04-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_register_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Guest_name', models.CharField(max_length=100)),
                ('Guest_email', models.CharField(max_length=100)),
                ('Item_name', models.CharField(max_length=500)),
                ('grand_Total', models.CharField(max_length=100)),
                ('Payment_method', models.CharField(max_length=100)),
            ],
        ),
    ]
